import FA
import KMP

if __name__ == "__main__":

    print("TEST 1")
    x =  FA.run_app("101010", "test1.txt")
    y =  KMP.run_app("101010", "test1.txt")
    # y = KMP.KMP_matcher(text1, "101010")
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 1.2")
    x =  FA.run_app("000000000", "test1.txt")
    y =  KMP.run_app("000000000", "test1.txt")
    # y = KMP.KMP_matcher(text1, "000000000")
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 2")
    x =  FA.run_app('\/', "test2.txt")
    y =  KMP.run_app('\/', "test2.txt")
    # y = KMP.KMP_matcher(text2, '\/\ ')
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 2.2")
    x =  FA.run_app('///', "test2.txt")
    y =  KMP.run_app('///', "test2.txt")
    # y = KMP.KMP_matcher(text2, '///')
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 3")
    x =  FA.run_app('ąą', "test3.txt")
    y =  KMP.run_app('ąą', "test3.txt")
    # y = KMP.KMP_matcher(text3, '///')
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 3.2")
    x =  FA.run_app('  ', "test3.txt")
    y =  KMP.run_app('  ', "test3.txt")
    # y = KMP.KMP_matcher(text3, '  ')
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 4")
    x = FA.run_app("αβα", "test4.txt")
    y = KMP.run_app("αβα", "test4.txt")
    # y = KMP.KMP_matcher(text4, "αβα")
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 4.2")
    x =  FA.run_app('γδ', "test4.txt")
    y =  KMP.run_app('γδ', "test4.txt")
    # y = KMP.KMP_matcher(text4, 'γδ')
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()

    print("TEST 5")
    x = FA.run_app('bred', "test5.txt")
    y = KMP.run_app('bred', "test5.txt")
    # y = KMP.KMP_matcher(text5, 'bred')
    # print("FA: ", x)
    # print("KMP: ", y)
    # print("To samo? ", x == y)
    print()
